[package]
name = "min-gba"
version = "0.1.0"
authors = ["Lokathor <zefria@gmail.com>"]
edition = "2018"
license = "Zlib OR Apache-2.0 OR MIT"

publish = false

[dependencies]

[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"
